export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const SELECT_CARD = 'SELECT_CARD'

export const REQUEST_USERS = 'REQUEST_USERS'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const SEARCH_USER = 'SEARCH_USER'
export const SELECT_USER = 'SELECT_USER'
export const ADD_USER_TO_GAME = 'ADD_USER_TO_GAME'
